---------
version: 1.0
mailbox:
  address: foo@example.com
  credentials:
    login: foo
    password: 123
  smtp_server:
    host: localhost
    authentication_type: starttls # tls, ssl or no (no authentication)
    port: 465
  imap_server:
    host: localhost
    authentication_type: ssl # tls or no (no authentication)
    port: 993
report:
  extension: xlsx
  suffix: _WeeklyActualandPlans
sites:
  - site: Abidjan Sud
    abbreviated: ABJS
    agents:
      - agent: Roland KOFFI
        mail_address: roland.koffi@example.com
      - agent: Sery ASSALE
        mail_address: sery.assale@example.com
  - site: Abidjan Nord
    abbreviated: ABJN
    agents:
      - agent: Séraphin TIZIE
        mail_address: seraphin.tizie@example.com
      - agent: Akissi NETA
        mail_address: akissi.neta@example.com
      - agent: Flore MABEA
        mail_address: flore.mabea@example.com
storage:
  path: "emails" # relative or absolute path