settings:
  mailbox:
    address: foo@example.com
    credentials:
      login: foo
      password: 123
    smtp_server:
      host: localhost
      ssl_tls: true
      port: 465
    imap_server:
      host: localhost
      ssl_tls: true
      port: 993
